namespace Global.TradingPlatform.OrderService
{
    public class Execution
    {
        public int ExecutionID { get; set; } // identity ID in DB
        public int OrderID { get; set; } // FK
        public Guid OperationNumber { get; set; } // generated by market

        public int OrderQty { get; set; }
        public int LastShares { get; set; }
        public int CumulativeQty { get; set; }
        public int LeavesQuantity { get; set; }

        public string Status { get; set; } // Accpeted, PartiallyFilled, Filled, Cancelled

        public DateTime OperationTime { get; set; }

        // Navigation property
        public Order Order { get; set; }
    }
}
